#include "Entity.h"

// 1.18.2 EntityType.java 注册表顺序（注册顺序 = 协议 ID）
EntityType entityTypeFromProtocolId(int typeId) {
    // 有效范围：0 ~ static_cast<int>(EntityType::FISHING_BOBBER)
    if (typeId >= 0 && typeId <= static_cast<int>(EntityType::FISHING_BOBBER)) {
        return static_cast<EntityType>(typeId);
    }
    return EntityType::UNKNOWN;
}

static const char* ENTITY_TYPE_NAMES[] = {
        "area_effect_cloud",
        "armor_stand",
        "arrow",
        "axolotl",
        "bat",
        "bee",
        "blaze",
        "boat",
        "cat",
        "cave_spider",
        "chicken",
        "cod",
        "cow",
        "creeper",
        "dolphin",
        "donkey",
        "dragon_fireball",
        "drowned",
        "elder_guardian",
        "end_crystal",
        "ender_dragon",
        "enderman",
        "endermite",
        "evoker",
        "evoker_fangs",
        "experience_orb",
        "eye_of_ender",
        "falling_block",
        "firework_rocket",
        "fox",
        "ghast",
        "giant",
        "glow_item_frame",
        "glow_squid",
        "goat",
        "guardian",
        "hoglin",
        "horse",
        "husk",
        "illusioner",
        "iron_golem",
        "item",
        "item_frame",
        "fireball",
        "leash_knot",
        "lightning_bolt",
        "llama",
        "llama_spit",
        "magma_cube",
        "marker",
        "minecart",
        "chest_minecart",
        "command_block_minecart",
        "furnace_minecart",
        "hopper_minecart",
        "spawner_minecart",
        "tnt_minecart",
        "mule",
        "mooshroom",
        "ocelot",
        "painting",
        "panda",
        "parrot",
        "phantom",
        "pig",
        "piglin",
        "piglin_brute",
        "pillager",
        "polar_bear",
        "tnt",
        "pufferfish",
        "rabbit",
        "ravager",
        "salmon",
        "sheep",
        "shulker",
        "shulker_bullet",
        "silverfish",
        "skeleton",
        "skeleton_horse",
        "slime",
        "small_fireball",
        "snow_golem",
        "snowball",
        "spectral_arrow",
        "spider",
        "squid",
        "stray",
        "strider",
        "egg",
        "ender_pearl",
        "experience_bottle",
        "potion",
        "trident",
        "trader_llama",
        "tropical_fish",
        "turtle",
        "vex",
        "villager",
        "vindicator",
        "wandering_trader",
        "witch",
        "wither",
        "wither_skeleton",
        "wither_skull",
        "wolf",
        "zoglin",
        "zombie",
        "zombie_horse",
        "zombie_villager",
        "zombified_piglin",
        "player",
        "fishing_bobber"
};

// 编译期断言：确保数组大小和枚举数量匹配，防止后续维护时遗漏
static_assert(sizeof(ENTITY_TYPE_NAMES) / sizeof(ENTITY_TYPE_NAMES[0]) ==
              static_cast<size_t>(EntityType::FISHING_BOBBER) + 1,
              "Entity name array size mismatch with enum count!");

const char* Entity::getTypeName() const {
    int idx = static_cast<int>(type);
    if (idx >= 0 && idx <= static_cast<int>(EntityType::FISHING_BOBBER)) {
        return ENTITY_TYPE_NAMES[idx];
    }
    return "unknown";
}